local palette = {
	base = "#303446",
	surface0 = "#414559",
	surface1 = "#51576d",
	surface2 = "#626880",
	overlay0 = "#737994",
	overlay1 = "#838ba7",
	overlay2 = "#949cbb",
	text = "#c6d0f5",
	subtext1 = "#b5bfe2",
	subtext0 = "#a5adce",
	rosewater = "#f2d5cf",
	flamingo = "#eebebe",
	pink = "#f4b8e4",
	mauve = "#ca9ee6",
	red = "#e78284",
	maroon = "#ea999c",
	peach = "#ef9f76",
	yellow = "#e5c890",
	green = "#a6d189",
	teal = "#81c8be",
	sky = "#99d1db",
	sapphire = "#85c1dc",
	blue = "#8caaee",
	lavender = "#babbf1",
}

return {
	palette = palette,

	background = palette.base,
	grid_background = "#1e2030",
	grid_line = palette.surface0,
	grid_beat_line = palette.surface1,

	piano_key_white = "#e6e9ef",
	piano_key_black = "#292c3c",
	piano_key_white_text = "#4c4f69",
	piano_key_black_text = palette.text,
	piano_key_separator = palette.surface1,

	scale_root_grid = palette.blue,
	scale_root_grid_alpha = 40,
	scale_note_grid = palette.lavender,
	scale_note_grid_alpha = 30,
	scale_root_piano = palette.blue,
	scale_note_piano = palette.lavender,

	note_default = palette.blue,

	playhead = palette.rosewater,
	playhead_alpha = 200,

	statusline_bg = "#292c3c",
	statusline_bg_alpha = 0.95,
	statusline_text = palette.text,
	statusline_separator = palette.surface1,
	statusline_bpm = palette.yellow,
	statusline_highlight_on = palette.green,
	statusline_highlight_off = palette.surface2,

	voice_colors = {
		palette.peach,
		palette.yellow,
		palette.green,
		palette.blue,
		palette.mauve,
		palette.pink,
		palette.red,
		palette.overlay1,
	},
}
