#pragma once

#define MSDFGEN_PUBLIC 
#define MSDFGEN_EXT_PUBLIC 

#define MSDFGEN_VERSION "1.10"
#define MSDFGEN_VERSION_MAJOR 1
#define MSDFGEN_VERSION_MINOR 10
#define MSDFGEN_VERSION_REVISION 0
#define MSDFGEN_COPYRIGHT_YEAR 2024
